### ISSUE TITLE
File not found error when doing HDD

### ISSUE THREAD

**Issue by amordahl** [Pancax/SADeltaDebugger#1]
Got this trying to delta debug dacapo from wala results:

```
Running command [jdeps, -R, -verbose, -dotoutput, /results/wala/dacapo-2006/campaign0/violations/deltadebugging/VIOLATION/DIRECT/e82ba2d048f87920ad55f21c154fdf16/a6fa0ca8c
9cf937d0197282db48ef122/reflectionSetting/NO_FLOW_TO_CASTS/MST/NO_FLOW_TO_CASTS_APPLICATION_GET_METHOD/NO_FLOW_TO_CASTS_APPLICATION_GET_METHOD/MPT/NO_FLOW_TO_CASTS/eclipse
.jar/0/benchmarks/Dacapo-2006/benchmarks/deps/classes/dotfiles, /results/wala/dacapo-2006/campaign0/violations/deltadebugging/VIOLATION/DIRECT/e82ba2d048f87920ad55f21c154f
df16/a6fa0ca8c9cf937d0197282db48ef122/reflectionSetting/NO_FLOW_TO_CASTS/MST/NO_FLOW_TO_CASTS_APPLICATION_GET_METHOD/NO_FLOW_TO_CASTS_APPLICATION_GET_METHOD/MPT/NO_FLOW_TO
_CASTS/eclipse.jar/0/benchmarks/Dacapo-2006/benchmarks/deps/classes]

java.io.FileNotFoundException: /results/wala/dacapo-2006/campaign0/violations/deltadebugging/VIOLATION/DIRECT/e82ba2d048f87920ad55f21c154fdf16/a6fa0ca8c9cf937d0197282db48e
f122/reflectionSetting/NO_FLOW_TO_CASTS/MST/NO_FLOW_TO_CASTS_APPLICATION_GET_METHOD/NO_FLOW_TO_CASTS_APPLICATION_GET_METHOD/MPT/NO_FLOW_TO_CASTS/eclipse.jar/0/benchmarks/D
acapo-2006/benchmarks/deps/classes/dotfiles/classes.dot (No such file or directory)

        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at java.base/java.util.Scanner.<init>(Scanner.java:639)
        at cs.utd.soles.classgraph.DependencyGraph.parseGraphFromDot(DependencyGraph.java:24)
        at cs.utd.soles.reduction.BinaryReduction.createDependencyNodes(BinaryReduction.java:118)
        at cs.utd.soles.reduction.BinaryReduction.reduce(BinaryReduction.java:38)

        at cs.utd.soles.Runner.main(Runner.java:117)

Exception in thread "main"
java.lang.NullPointerException

        at cs.utd.soles.reduction.BinaryReduction.reduce(BinaryReduction.java:39)
        at cs.utd.soles.Runner.main(Runner.java:117)
```

**Comment by Pancax** [comment]
fixed in https://github.com/Pancax/SADeltaDebugger/commit/59e04aafdbe896de9a973f025fecdfdf64d2e250
